spring:
  application:
    name: GreengramVer1
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/greengram2024_v1
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 20MB


mybatis:
  mapper-locations: mappers/**/*.xml

springdoc:
  api-docs:
    version: openapi_3_1
  swagger-ui:
    path: /swagger
    operations-sorter: method
    default-model-expand-depth: 10
    cache:
      disabled: true
    display-request-duration: true

server:
  port: 8080

file:
  dir: D:\download\greengram_ver1\

---

spring:
  config:
    activate:
      on-profile: test

file:
  dir: D:\download\greengram_ver1\